
import ContactForm from "@/Component/ContactForm";
import ContactHero from "@/Component/ContactHero";
import ContactInfo from "@/Component/ContactInfo";
import Footer from "@/Component/Footer";
import Header from "@/Component/Header";
import LayoutProvider from "@/Component/LayoutProvider";
import Newsletter from "@/Component/Newsletter";
import React from "react";


export function generateMetadata() {
  return {
    title: "Contact", 
    description: "Generated by create next app"
  }
};


const Contact = () => {
  

  return (
    <>
      <LayoutProvider>
        <Header />
        <ContactHero
        title={"________ Get in Touch"}
        heading1={"We’d love to hear "}
        heading2={" from you."}
        className={'text-primary-blue100'}
        para={"“Crown International Technology: Redefining the Digital Frontier Unlocking Digital Potential, Empowering Global Progress.”"}
        />
        <ContactInfo />
        <ContactForm />
        <Newsletter />
        <Footer />
      </LayoutProvider>
    </>
  );
};

export default Contact;

